### ISSUE TITLE
Season 4 To-Do

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-stake#55]
Given the current implementation of Staking Season 4, which basically follows the exact same behaviors as in Season 3, also bears the same "shortcut" implementation in mind, especially regarding the "dynamic block/allow" at run time https://github.com/hoprnet/hopr-devrel/issues/205#issuecomment-1108450154

Although the season 4 smart contract is developed and deployed at the same time as the season 3 (see https://github.com/hoprnet/hopr-devrel/issues/205), it is still possible to adjust and/or redeploy the contract.

At the moment, the following NFT types are blocked at deployment, as specified in https://github.com/hoprnet/hopr-devrel/issues/205, precisely speaking:
```Solidity
_ownerBlockNftType(2); // HODLr
_ownerBlockNftType(3); // Wildhorn_v1
_ownerBlockNftType(4); // PuzzleHunt_v1
_ownerBlockNftType(7); // PuzzleHunt_v2
_ownerBlockNftType(8); // Wildhorn_v2
_ownerBlockNftType(9); // DAO_v2
_ownerBlockNftType(10); // Surveyor
```

If there are simply more NFTs to be blocked/allowed, before the start of Season 4
- [ ]  owner can call `ownerBlockNftType` or `ownerUnblockNftType` functions in the deployed S4 contract (See addresses in https://github.com/hoprnet/hopr-stake/pull/53)

If the contract needs to be redeployed, before the start of Season 4
- [ ] Develop, test and deploy new season 4 smart contracts, with https://github.com/hoprnet/hopr-stake/issues/52 in mind
- [ ] Develop and deploy a new season 4 subgraph as in https://github.com/hoprnet/hopr-devrel/pull/223

**Comment by tolbrino** [comment]
@QYuQianchen I suspect this can be closed?
